[package]
name = "otree"
version = "0.2.0"
edition = "2021"
build = "build.rs"
license = "MIT"
authors = ["fioncat"]
categories = ["command-line-utilities"]
readme = "README.md"
repository = "https://github.com/fioncat/otree"
description = "A command line tool to view objects (json/yaml/toml) in TUI tree widget"

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.18", features = ["derive"] }
crossterm = "0.28.1"
dirs = "5.0.1"
humansize = "2.1.3"
once_cell = "1.19.0"
paste = "1.0.15"
ratatui = "0.28.1"
regex = "1.10.6"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = { version = "1.0.128", features = ["preserve_order"] }
serde_yml = "0.0.12"
toml = { version = "0.8.19", features = ["preserve_order"] }
tui-tree-widget = "0.22.0"

[build-dependencies]
simple-error = "0.3.0"
vergen = { version = "9.0.1", features = ["build", "rustc", "cargo", "si"] }

[profile.release]
lto = true
strip = true
incremental = false
