[package]
name = "otree"
version = "0.1.0"
edition = "2021"
build = "build.rs"
license = "MIT"
authors = ["fioncat"]
categories = ["command-line-utilities"]
readme = "README.md"
repository = "https://github.com/fioncat/otree"
description = "A command line tool to view objects (json/yaml/toml) in TUI tree widget"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.4", features = ["derive"] }
crossterm = "0.27.0"
dirs = "5.0.1"
paste = "1.0.15"
ratatui = "0.26.2"
serde = { version = "1.0.202", features = ["derive"] }
serde_json = { version = "1.0.117", features = ["preserve_order"] }
serde_yml = "0.0.7"
toml = { version = "0.8.13", features = ["preserve_order"] }
tui-tree-widget = "0.19.0"

[build-dependencies]
simple-error = "0.3.0"
vergen = { version = "8.3.1", features = ["build", "rustc", "cargo", "si"] }

[profile.release]
lto = true
strip = true
incremental = false
