[package]
name = "otree"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.83"
crossterm = "0.27.0"
paste = "1.0.15"
ratatui = "0.26.2"
serde = { version = "1.0.201", features = ["derive"] }
serde_json = { version = "1.0.117", features = ["preserve_order"] }
serde_yml = "0.0.7"
toml = { version = "0.8.12", features = ["preserve_order"] }
tui-tree-widget = "0.19.0"
