[package]
name = "otree"
version = "0.2.0"
edition = "2021"
build = "build.rs"
license = "MIT"
authors = ["fioncat"]
categories = ["command-line-utilities"]
readme = "README.md"
repository = "https://github.com/fioncat/otree"
description = "A command line tool to view objects (json/yaml/toml) in TUI tree widget"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.7", features = ["derive"] }
crossterm = "0.27.0"
dirs = "5.0.1"
humansize = "2.1.3"
once_cell = "1.19.0"
paste = "1.0.15"
ratatui = "0.26.3"
regex = "1.10.5"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = { version = "1.0.118", features = ["preserve_order"] }
serde_yml = "0.0.10"
toml = { version = "0.8.14", features = ["preserve_order"] }
tui-tree-widget = { git = "https://github.com/EdJoPaTo/tui-rs-tree-widget.git", rev = "dceb9f87b0afc12695b633d17f7f86690a2ec682" }

[build-dependencies]
simple-error = "0.3.0"
vergen = { version = "8.3.1", features = ["build", "rustc", "cargo", "si"] }

[profile.release]
lto = true
strip = true
incremental = false
